# Generated by Django 4.2.2 on 2023-09-02 21:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatApi', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='RoomModel',
        ),
    ]
