# Generated by Django 4.2.2 on 2023-09-04 12:37

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chatApi', '0004_remove_roommodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from=['name'], unique=True),
        ),
    ]
